class Users::RegistrationsController < Devise::RegistrationsController
  #Before saving user to DB check which form they are on and save the parameter
  def create
    premium = "prod_IcbXmtGhBK5dph"
    
    super do |resource|
      if params[:subscription]
        resource.subscription_id = params[:subscription]
        #Product ID generated by stripe
        if resource.subscription_id == premium
          resource.save_with_subscription
        else
          resource.save
        end
      end
    end
  end
end